- name: rescan iscsi sessions
  shell: iscsiadm -m session --rescan && iscsiadm -m session -P3 | grep "Attached.*running"
  register: out
  until: out.rc == 0 
  retries: 5
  delay: 10

- name: pause after rescan
  pause:
    seconds: 20

- name: Collect linux facts
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - hardware 

#- name: Create a new primary partition
#  parted:
#    device: "/dev/{{ item.key }}"
#    number: 1
#    state: present
#  with_dict: "{{ ansible_devices }}"
#  when: item.value.vendor == vendor

- name: Create a xfs filesystem
  filesystem:
    fstype: xfs
    dev: "/dev/{{ item.key }}"
    force: yes
  with_dict: "{{ ansible_devices }}"
  when: item.value.vendor == vendor

- name: Mount up Nexenta disk
  mount:
    path: "/mnt/san"
    src:  "/dev/{{ item.key }}" 
    fstype: xfs
    opts: noatime,noauto
    state: mounted
  with_dict: "{{ ansible_devices }}"
  when: item.value.vendor == vendor

