---
- name: FS tcm configuration - hostname and packages
  hosts: all
  gather_facts: no
  user: root
  tasks:
  # Configuration tasks
  - name: Wait 900 seconds, but only start checking after 60 seconds
    wait_for_connection:
      timeout: 1200

  - name: gather_facts
    setup:

  - import_tasks: includes/set_host_name.yml
    when: ansible_system == 'Linux'

  - name: include install linux pkgs
    import_tasks: includes/install_linux.yml
    when: ansible_system == 'Linux'


#  - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
#    lineinfile:
#      path: /etc/netplan/01-netcfg.yaml
#      line: "    ens224:\n      dhcp4: yes"
#    when: ansible_facts['distribution'] == 'Ubuntu'
# 
