- hosts: iSCSI
  vars_files:
    - group_vars/all.yml
  gather_facts: yes
  user: root

  tasks:
  - name: Create new iSCSI target 
    import_tasks: includes/iscsi/ns_conf_target_tg_hg_vol_map.yml
  - name: Linux mkfs and mount
    import_tasks: includes/iscsi/linux_format_xfs_mount_iscsi_disk.yml
  - name: Enable WBC
    import_tasks: includes/ns_lun_wbc.yml
    delegate_to: localhost
    run_once: True
  - name: delete
    import_tasks: includes/iscsi/ns_unconf.yml
    when: delete is defined
    ignore_errors: yes
