- name: Install pkgs
  apt:
    name:
        - nfs-common
        - cifs-utils
        - rpcbind
        - autofs
        - fio
          #- openjdk-8-jre
          #- open-iscsi
          #- csh
          #- unzip
    state: present 
  async: 1000
  poll: 0
  register: install_sleeper

