- name: Get LUNs GUIDs 0_0
  nef:
    user: "{{ nef_user }}"
    password: "{{ nef_password }}"
    host: "{{ nef_host }}"
    method: get
    path: 'san/logicalUnits?fields=guid%2CvolSize'
  register: outp

- set_fact:
    guid: "{{ outp | json_query(jq) | lower }}"
  vars:
    jq: "data[?volSize==`32768000000`].guid"
        #  until: result | json_query(query) == ['running'] != -1
        #  vars:
        #    query: '[?contains(volume, `vg-is-ans`)]'

- name: Enable writebackcache
  nef:
    user: "{{ nef_user }}"
    password: "{{ nef_password }}"
    host: "{{ nef_host }}"
    method: put
    path: "san/logicalUnits/{{ item }}"
    payload:
      writebackCacheDisabled: false
  async: 1000
  poll: 0
  loop: "{{ guid }}"
  register: wbc_sleeper

- name: Include waiter for wbc
  include_tasks: _wait_for_asynchronous_job2end.yml
  vars: 
    list_of_results: "{{ wbc_sleeper.results }}"

